services:
    dev-db:
        image: mysql:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mapv
        networks:
            - mapv
networks:
    mapv:
